### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by Ankur-Deka** [rosewang2008/gym-cooking#2]
Congratulations on your nice paper and the award! I noticed a small typo in the folder `gym_cooking/misc/game/graphics` - `plate.png` should be renamed to `Plate.png`

**Comment by rosewang2008** [comment]
Thanks @Ankur-Deka! Is the filename affecting the game loading?

**Comment by rosewang2008** [comment]
If there's a concrete issue with the filename (e.g. in running an experiment), please feel free to update this issue.

**Comment by Ankur-Deka** [comment]
Sorry for my late reply. When I run the code, I get the following error:
```
python main.py --num-agents 2 --level open-divider_salad --play
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Subtasks: [Deliver(Lettuce-Plate-Tomato), Chop(Lettuce), Merge(Tomato, Plate), Merge(Lettuce, Plate), Chop(Tomato), Merge(Tomato, Lettuce-Plate), Merge(Lettuce-Tomato, Plate), Merge(Lettuce, Tomato), Merge(Lettuce, Plate-Tomato)] 

Traceback (most recent call last):
  File "main.py", line 126, in <module>
    game.on_execute()
  File "/home/ankur/MSR_Research_Home/gym-cooking/gym_cooking/misc/game/gameplay.py", line 67, in on_execute
    self.on_render()
  File "/home/ankur/MSR_Research_Home/gym-cooking/gym_cooking/misc/game/game.py", line 70, in on_render
    self.draw_object(o)
  File "/home/ankur/MSR_Research_Home/gym-cooking/gym_cooking/misc/game/game.py", line 126, in draw_object
    self.draw('Plate', self.tile_size, self.scaled_location(obj.location))
  File "/home/ankur/MSR_Research_Home/gym-cooking/gym_cooking/misc/game/game.py", line 102, in draw
    image = pygame.transform.scale(get_image(image_path), size)
  File "/home/ankur/MSR_Research_Home/gym-cooking/gym_cooking/misc/game/game.py", line 15, in get_image
    image = pygame.image.load(canonicalized_path)
pygame.error: Couldn't open misc/game/graphics/Plate.png
```

The error disappears after I rename 'plate.png' to 'Plate.png' and the code runs perfectly - it's fun to virtually prepare salad :+1: .

**Comment by rosewang2008** [comment]
Thanks @Ankur-Deka for the clarification! That's odd - it seems like my file parsing is fine when I run the command. Thanks for letting me know about this.
